services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: punks_offchain
      POSTGRES_PASSWORD: punks_offchain
      POSTGRES_DB: punks_offchain
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  pgdata:
