packages:
  - contracts
  - docs
  - images
  - indexer
  - offchain
  - sdk
  - punksmarket.app
  - punks.auction

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@reown/appkit'
  - better-sqlite3
  - esbuild
  - iso-constants
  - keccak
  - node-datachannel
  - protobufjs
  - secp256k1
  - vue-demi
