import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'

import type { Context } from 'ponder:registry'
import { backfillMarker, ethUsdPrice } from 'ponder:schema'

const SECONDS_PER_DAY = 86_400n
const WEI_PER_ETH = 1_000_000_000_000_000_000n // 1e18

// Chainlink ETH/USD uses 8 decimals. `current * 100 / 1e8 = current / 1e6`
// gives cents. We keep the multiplication explicit so the scaling is obvious.
const CHAINLINK_ETH_USD_DECIMALS = 8n
const CHAINLINK_TO_CENTS_DIVISOR = 10n ** (CHAINLINK_ETH_USD_DECIMALS - 2n) // 1e6

// How far back to walk when the event's own UTC day has no price row yet
// (sale fires before the day's first AnswerUpdated). One week bridges
// weekend / quiet periods without ever stamping a wildly stale price.
const PRICE_LOOKBACK_DAYS = 7n

export const PRICE_SOURCE_CHAINLINK = 'chainlink'
export const PRICE_SOURCE_CSV = 'csv:pre_chainlink_v1'

// Bump this name when the CSV contents change so the seed re-runs on next
// start. Matches the `chainlink:` suffix style above so both sources are
// versioned uniformly.
const PRE_CHAINLINK_SEED_NAME = 'eth_usd_pre_chainlink_csv_v1'

// Resolved from the package root (`pnpm dev` / `pnpm start` always cd into
// the indexer dir, and the Dockerfile sets `WORKDIR /app/indexer`). This is
// more robust than `import.meta.url` because Ponder may bundle handlers.
const PRE_CHAINLINK_CSV_PATH = resolve(
  process.cwd(),
  'data',
  'eth_usd_pre_chainlink.csv',
)
const DB_INSERT_CHUNK = 500

export function dayUnix(timestamp: bigint): bigint {
  return (timestamp / SECONDS_PER_DAY) * SECONDS_PER_DAY
}

export function chainlinkAnswerToCents(answer: bigint): bigint {
  if (answer <= 0n) return 0n
  return answer / CHAINLINK_TO_CENTS_DIVISOR
}

// Convert wei → USD cents using the price snapshot most recently indexed for
// the event's UTC day (or the nearest preceding day, up to a week back).
// Returns `null` only if no price row exists at all in that window — which
// after the CSV seed runs should be impossible for any CryptoPunks-era event.
export async function usdCentsForWei(
  context: Context,
  weiAmount: bigint,
  timestamp: bigint,
): Promise<bigint | null> {
  if (weiAmount === 0n) return 0n
  const ethUsdCents = await ethUsdCentsForTimestamp(context, timestamp)
  if (ethUsdCents === null) return null
  return (weiAmount * ethUsdCents) / WEI_PER_ETH
}

async function ethUsdCentsForTimestamp(
  context: Context,
  timestamp: bigint,
): Promise<bigint | null> {
  const day = dayUnix(timestamp)
  for (let i = 0n; i <= PRICE_LOOKBACK_DAYS; i++) {
    const candidate = day - i * SECONDS_PER_DAY
    const row = await context.db.find(ethUsdPrice, { day_unix: candidate })
    if (row) return row.eth_usd_cents
  }
  return null
}

// Seeds `eth_usd_prices` from the bundled pre-Chainlink CSV. Idempotent via a
// `backfill_markers` sentinel row. Runs once at indexer startup before the
// first event handler so even the earliest V1 sale has USD context.
//
// The CSV is committed to the repo under `data/eth_usd_pre_chainlink.csv` and
// was generated by `scripts/fetch-pre-chainlink-prices.ts` — the runtime
// loader does *not* hit any external API.
export async function seedPreChainlinkPrices(context: Context): Promise<void> {
  const existing = await context.db.find(backfillMarker, {
    name: PRE_CHAINLINK_SEED_NAME,
  })
  if (existing) return

  const rows = await readPreChainlinkCsv()
  if (rows.length === 0) {
    // CSV missing or empty — leave the marker absent so a future start that
    // ships a fresh CSV gets a chance to seed. Better than silently masking a
    // packaging bug behind a "seeded" marker.
    return
  }

  const nowSec = BigInt(Math.floor(Date.now() / 1000))
  const inserts = rows.map((r) => ({
    day_unix: r.day_unix,
    eth_usd_cents: r.eth_usd_cents,
    source: PRICE_SOURCE_CSV,
    chainlink_round_id: null,
    chainlink_updated_at: null,
    block_number: null,
    updated_at: nowSec,
  }))

  for (const chunk of chunked(inserts, DB_INSERT_CHUNK)) {
    await context.db.insert(ethUsdPrice).values(chunk).onConflictDoNothing()
  }

  await context.db.insert(backfillMarker).values({
    name: PRE_CHAINLINK_SEED_NAME,
    completed_at: nowSec,
  })
}

type CsvRow = { day_unix: bigint; eth_usd_cents: bigint }

async function readPreChainlinkCsv(): Promise<CsvRow[]> {
  let raw: string
  try {
    raw = await readFile(PRE_CHAINLINK_CSV_PATH, 'utf8')
  } catch {
    return []
  }
  const rows: CsvRow[] = []
  const lines = raw.split('\n')
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!.trim()
    if (!line) continue
    if (i === 0 && line.startsWith('day_unix')) continue
    const [dayStr, centsStr] = line.split(',')
    if (!dayStr || !centsStr) continue
    const day = BigInt(dayStr)
    const cents = BigInt(centsStr)
    if (cents <= 0n) continue
    rows.push({ day_unix: day, eth_usd_cents: cents })
  }
  return rows
}

function chunked<T>(items: readonly T[], size: number): T[][] {
  if (items.length === 0) return []
  const out: T[][] = []
  for (let i = 0; i < items.length; i += size) {
    out.push(items.slice(i, i + size) as T[])
  }
  return out
}
