/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AuthSessionTransformer from '#transformers/auth_session_transformer'
import type InquiryTransformer from '#transformers/inquiry_transformer'
import type SearchMatchTransformer from '#transformers/search_match_transformer'
import type SearchTransformer from '#transformers/search_transformer'
import type UserAddressTransformer from '#transformers/user_address_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type AuthSession = InferData<AuthSessionTransformer>
  export namespace AuthSession {
    export type Variants = InferVariants<AuthSessionTransformer>
  }
  export type Inquiry = InferData<InquiryTransformer>
  export namespace Inquiry {
    export type Variants = InferVariants<InquiryTransformer>
  }
  export type SearchMatch = InferData<SearchMatchTransformer>
  export namespace SearchMatch {
    export type Variants = InferVariants<SearchMatchTransformer>
  }
  export type Search = InferData<SearchTransformer>
  export namespace Search {
    export type Variants = InferVariants<SearchTransformer>
  }
  export type UserAddress = InferData<UserAddressTransformer>
  export namespace UserAddress {
    export type Variants = InferVariants<UserAddressTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
