services:
  postgres:
    image: postgres:17-alpine
    container_name: punks-indexer-db
    environment:
      POSTGRES_USER: punks
      POSTGRES_PASSWORD: punks
      POSTGRES_DB: punks
    ports:
      - '5412:5432'
    volumes:
      - punks_indexer_db:/var/lib/postgresql/data

volumes:
  punks_indexer_db:
