TRAIT_NAMES = (
  "Alien",
  "Ape",
  "Female",
  "Male",
  "Zombie",
  "Alien",
  "Ape",
  "Female 1",
  "Female 2",
  "Female 3",
  "Female 4",
  "Male 1",
  "Male 2",
  "Male 3",
  "Male 4",
  "Zombie",
  "0 Attributes",
  "1 Attributes",
  "2 Attributes",
  "3 Attributes",
  "4 Attributes",
  "5 Attributes",
  "6 Attributes",
  "7 Attributes",
  "3D Glasses",
  "Bandana",
  "Beanie",
  "Big Beard",
  "Big Shades",
  "Black Lipstick",
  "Blonde Bob",
  "Blonde Short",
  "Blue Eye Shadow",
  "Buck Teeth",
  "Cap",
  "Cap Forward",
  "Chinstrap",
  "Choker",
  "Cigarette",
  "Classic Shades",
  "Clown Eyes Blue",
  "Clown Eyes Green",
  "Clown Hair Green",
  "Clown Nose",
  "Cowboy Hat",
  "Crazy Hair",
  "Dark Hair",
  "Do-rag",
  "Earring",
  "Eye Mask",
  "Eye Patch",
  "Fedora",
  "Front Beard",
  "Front Beard Dark",
  "Frown",
  "Frumpy Hair",
  "Goat",
  "Gold Chain",
  "Green Eye Shadow",
  "Half Shaved",
  "Handlebars",
  "Headband",
  "Hoodie",
  "Horned Rim Glasses",
  "Hot Lipstick",
  "Knitted Cap",
  "Luxurious Beard",
  "Medical Mask",
  "Messy Hair",
  "Mohawk",
  "Mohawk Dark",
  "Mohawk Thin",
  "Mole",
  "Mustache",
  "Muttonchops",
  "Nerd Glasses",
  "Normal Beard",
  "Normal Beard Black",
  "Orange Side",
  "Peak Spike",
  "Pigtails",
  "Pilot Helmet",
  "Pink With Hat",
  "Pipe",
  "Police Cap",
  "Purple Eye Shadow",
  "Purple Hair",
  "Purple Lipstick",
  "Red Mohawk",
  "Regular Shades",
  "Rosy Cheeks",
  "Shadow Beard",
  "Shaved Head",
  "Silver Chain",
  "Small Shades",
  "Smile",
  "Spots",
  "Straight Hair",
  "Straight Hair Blonde",
  "Straight Hair Dark",
  "Stringy Hair",
  "Tassle Hat",
  "Tiara",
  "Top Hat",
  "VR",
  "Vampire Hair",
  "Vape",
  "Welding Goggles",
  "Wild Blonde",
  "Wild Hair",
  "Wild White Hair",
)


def trait_name_for_id(trait_id: int) -> str:
  if 0 <= trait_id < len(TRAIT_NAMES):
    return TRAIT_NAMES[trait_id]
  return f"Trait {trait_id}"
