// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "../../app/app.config";
import type { default as appConfig1 } from "../../../node_modules/.pnpm/@1001-digital+layers.evm@2.7.7_ab75a583e8258af35912a57260230c1c/node_modules/@1001-digital/layers.evm/app/app.config";
import type { default as appConfig2 } from "../../../node_modules/.pnpm/@1001-digital+layers.base@2.0.24_magicast@0.5.3_vite@7.3.3_@types+node@22.19.18_jiti@2._a66a1379ca4fc4f075cabdb2a5d18d0a/node_modules/@1001-digital/layers.base/app/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1, typeof appConfig2]>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}

}
export {}