import type { Abi } from 'viem'

export const punksDataReadAbi = [
  { type: 'error', name: 'AlreadySealed', inputs: [] },
  { type: 'error', name: 'BlobTooLarge', inputs: [] },
  { type: 'error', name: 'BlobWriteFailed', inputs: [] },
  { type: 'error', name: 'InvalidChunkIndex', inputs: [] },
  { type: 'error', name: 'InvalidColorCount', inputs: [] },
  { type: 'error', name: 'InvalidColorId', inputs: [] },
  { type: 'error', name: 'InvalidCoordinate', inputs: [] },
  { type: 'error', name: 'InvalidHash', inputs: [] },
  { type: 'error', name: 'InvalidLength', inputs: [] },
  { type: 'error', name: 'InvalidMask', inputs: [] },
  { type: 'error', name: 'InvalidPixelCount', inputs: [] },
  { type: 'error', name: 'InvalidPunkId', inputs: [] },
  { type: 'error', name: 'InvalidScalar', inputs: [] },
  { type: 'error', name: 'InvalidTraitId', inputs: [] },
  { type: 'error', name: 'InvalidWordIndex', inputs: [] },
  { type: 'error', name: 'LengthOverflow', inputs: [] },
  { type: 'error', name: 'MalformedPixelBlob', inputs: [] },
  { type: 'error', name: 'NotOwner', inputs: [] },
  {
    type: 'error',
    name: 'ReadOutOfBounds',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'length', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'ZeroAddress', inputs: [] },
  {
    type: 'function',
    name: 'attributeCountOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorAt',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'x', type: 'uint8' },
      { name: 'y', type: 'uint8' },
    ],
    outputs: [{ name: 'colorId', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorBitmapWord',
    inputs: [
      { name: 'colorId', type: 'uint8' },
      { name: 'wordIndex', type: 'uint8' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorCountBitmapWord',
    inputs: [
      { name: 'colorCount', type: 'uint8' },
      { name: 'wordIndex', type: 'uint8' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorCountOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorMaskOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorOf',
    inputs: [{ name: 'colorId', type: 'uint8' }],
    outputs: [{ name: 'rgba', type: 'bytes4' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorSupply',
    inputs: [{ name: 'colorId', type: 'uint8' }],
    outputs: [{ name: 'pixels', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'datasetHash',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasColor',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'colorId', type: 'uint8' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasTrait',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'traitId', type: 'uint16' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasTraits',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'requiredMask', type: 'uint256' },
      { name: 'forbiddenMask', type: 'uint256' },
      { name: 'anyOfMask', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'headVariantOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'indexedPixelsOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isSealed',
    inputs: [],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isValidTraitId',
    inputs: [{ name: 'traitId', type: 'uint16' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paletteAlphaBytes',
    inputs: [],
    outputs: [{ name: 'alpha', type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paletteRgbBytes',
    inputs: [],
    outputs: [{ name: 'rgb', type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paletteRgbaBytes',
    inputs: [],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paletteSize',
    inputs: [],
    outputs: [{ type: 'uint16' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'pixelCountBitmapWord',
    inputs: [
      { name: 'pixelCount', type: 'uint16' },
      { name: 'wordIndex', type: 'uint8' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pixelCountOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkTypeOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'traitBitmapWord',
    inputs: [
      { name: 'traitId', type: 'uint16' },
      { name: 'wordIndex', type: 'uint8' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'traitCount',
    inputs: [],
    outputs: [{ type: 'uint16' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'traitKind',
    inputs: [{ name: 'traitId', type: 'uint16' }],
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'traitMaskOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'traitName',
    inputs: [{ name: 'traitId', type: 'uint16' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'traitSupply',
    inputs: [{ name: 'traitId', type: 'uint16' }],
    outputs: [{ type: 'uint16' }],
    stateMutability: 'view',
  },
] as const satisfies Abi

export const punksDataAbi = punksDataReadAbi

export const punksRendererReadAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'punksData', type: 'address' },
      { name: 'punksMarket', type: 'address' },
      { name: 'wrapper', type: 'address' },
      { name: 'c721Wrapper', type: 'address' },
      { name: 'reverseRegistrar', type: 'address' },
      { name: 'reverseName', type: 'string' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'error', name: 'InvalidBackground', inputs: [] },
  { type: 'error', name: 'InvalidTokenId', inputs: [] },
  {
    type: 'function',
    name: 'C721_WRAPPER',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PUNKS_DATA',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PUNKS_MARKET',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'WRAPPER',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'backgroundOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ name: 'rgba', type: 'bytes4' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'dataContract',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'metadataJson',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkAttributes',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ name: 'csv', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkImage',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ name: 'rgba', type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkMarketplacePng',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkMarketplaceSvg',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkPng',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'backgroundRgba', type: 'bytes4' },
    ],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkPng',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkSvg',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenURI',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
] as const satisfies Abi

export const punksRendererAbi = punksRendererReadAbi
