import type { Abi } from 'viem'

export const punksDataReadAbi = [
  { type: 'error', name: 'InvalidColorCount', inputs: [] },
  { type: 'error', name: 'InvalidColorId', inputs: [] },
  { type: 'error', name: 'InvalidCoordinate', inputs: [] },
  { type: 'error', name: 'InvalidMask', inputs: [] },
  { type: 'error', name: 'InvalidPixelCount', inputs: [] },
  { type: 'error', name: 'InvalidPunkId', inputs: [] },
  { type: 'error', name: 'InvalidTraitId', inputs: [] },
  { type: 'error', name: 'InvalidWordIndex', inputs: [] },
  { type: 'error', name: 'MalformedPixelBlob', inputs: [] },
  {
    type: 'error',
    name: 'ReadOutOfBounds',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'length', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'attributeCountOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorAt',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'x', type: 'uint8' },
      { name: 'y', type: 'uint8' },
    ],
    outputs: [{ name: 'colorId', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorBitmapWord',
    inputs: [
      { name: 'colorId', type: 'uint8' },
      { name: 'wordIndex', type: 'uint8' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorCountBitmapWord',
    inputs: [
      { name: 'colorCount', type: 'uint8' },
      { name: 'wordIndex', type: 'uint8' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorCountOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorMaskOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorOf',
    inputs: [{ name: 'colorId', type: 'uint8' }],
    outputs: [{ name: 'rgba', type: 'bytes4' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'colorSupply',
    inputs: [{ name: 'colorId', type: 'uint8' }],
    outputs: [{ name: 'pixels', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'datasetHash',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasColor',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'colorId', type: 'uint8' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasTrait',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'traitId', type: 'uint16' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasTraits',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'requiredMask', type: 'uint256' },
      { name: 'forbiddenMask', type: 'uint256' },
      { name: 'anyOfMask', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'headVariantOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'indexedPixelsOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isValidTraitId',
    inputs: [{ name: 'traitId', type: 'uint16' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'paletteAlphaBytes',
    inputs: [],
    outputs: [{ name: 'alpha', type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paletteRgbBytes',
    inputs: [],
    outputs: [{ name: 'rgb', type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paletteRgbaBytes',
    inputs: [],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paletteSize',
    inputs: [],
    outputs: [{ type: 'uint16' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'pixelCountBitmapWord',
    inputs: [
      { name: 'pixelCount', type: 'uint16' },
      { name: 'wordIndex', type: 'uint8' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pixelCountOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkTypeOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'traitBitmapWord',
    inputs: [
      { name: 'traitId', type: 'uint16' },
      { name: 'wordIndex', type: 'uint8' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'traitCount',
    inputs: [],
    outputs: [{ type: 'uint16' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'traitKind',
    inputs: [{ name: 'traitId', type: 'uint16' }],
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'traitMaskOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'traitName',
    inputs: [{ name: 'traitId', type: 'uint16' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'traitSupply',
    inputs: [{ name: 'traitId', type: 'uint16' }],
    outputs: [{ type: 'uint16' }],
    stateMutability: 'view',
  },
] as const satisfies Abi

export const punksDataAbi = punksDataReadAbi

export const punksRendererReadAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'punksData', type: 'address' },
      { name: 'punksMarket', type: 'address' },
      { name: 'wrapper', type: 'address' },
      { name: 'c721Wrapper', type: 'address' },
      { name: 'reverseRegistrar', type: 'address' },
      { name: 'reverseName', type: 'string' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'error', name: 'InvalidBackground', inputs: [] },
  { type: 'error', name: 'InvalidTokenId', inputs: [] },
  {
    type: 'function',
    name: 'C721_WRAPPER',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PUNKS_DATA',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PUNKS_MARKET',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'WRAPPER',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'backgroundOf',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ name: 'rgba', type: 'bytes4' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'dataContract',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'metadataJson',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkAttributes',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ name: 'csv', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkImage',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ name: 'rgba', type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkMarketplacePng',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkMarketplaceSvg',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkPng',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'backgroundRgba', type: 'bytes4' },
    ],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkPng',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkSvg',
    inputs: [{ name: 'punkId', type: 'uint16' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenURI',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
] as const satisfies Abi

export const punksRendererAbi = punksRendererReadAbi

export const legacyCryptoPunksDataAbi = [
  {
    type: 'function',
    name: 'punkImageSvg',
    inputs: [{ name: 'index', type: 'uint16' }],
    outputs: [{ name: 'svg', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkAttributes',
    inputs: [{ name: 'index', type: 'uint16' }],
    outputs: [{ name: 'text', type: 'string' }],
    stateMutability: 'view',
  },
] as const satisfies Abi

export const cryptoPunks721Abi = [
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'licensingTerms',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerOf',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenURI',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokensOfOwner',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ type: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkProxyForUser',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getApproved',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isApprovedForAll',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'operator', type: 'address' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'wrapPunk',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'wrapPunkBatch',
    inputs: [{ name: 'punkIndexes', type: 'uint256[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unwrapPunk',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unwrapPunkBatch',
    inputs: [{ name: 'punkIndexes', type: 'uint256[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'migrateLegacyWrappedPunks',
    inputs: [{ name: 'punkIndexes', type: 'uint256[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'rescuePunk',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'account', type: 'address' },
      { name: 'id', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'setApprovalForAll',
    inputs: [
      { name: 'operator', type: 'address' },
      { name: 'isApproved', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'id', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'id', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'id', type: 'uint256' },
      { name: 'data', type: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
] as const satisfies Abi

export const wrappedPunksAbi = [
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerOf',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenURI',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'baseURI',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenByIndex',
    inputs: [{ name: 'index', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenOfOwnerByIndex',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'index', type: 'uint256' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getApproved',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isApprovedForAll',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'operator', type: 'address' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proxyInfo',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkContract',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'registerProxy',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'mint',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'burn',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setApprovalForAll',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'approved', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
      { name: '_data', type: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setBaseURI',
    inputs: [{ name: 'baseUri', type: 'string' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unpause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const satisfies Abi

export const cryptoPunksMarketAbi = [
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'imageHash',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punksRemainingToAssign',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextPunkIndexToAssign',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkIndexToAddress',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punksOfferedForSale',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [
      { name: 'isForSale', type: 'bool' },
      { name: 'punkIndex', type: 'uint256' },
      { name: 'seller', type: 'address' },
      { name: 'minValue', type: 'uint256' },
      { name: 'onlySellTo', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkBids',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [
      { name: 'hasBid', type: 'bool' },
      { name: 'punkIndex', type: 'uint256' },
      { name: 'bidder', type: 'address' },
      { name: 'value', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingWithdrawals',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'offerPunkForSale',
    inputs: [
      { name: 'punkIndex', type: 'uint256' },
      { name: 'minSalePriceInWei', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'offerPunkForSaleToAddress',
    inputs: [
      { name: 'punkIndex', type: 'uint256' },
      { name: 'minSalePriceInWei', type: 'uint256' },
      { name: 'toAddress', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'punkNoLongerForSale',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'buyPunk',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'enterBidForPunk',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'acceptBidForPunk',
    inputs: [
      { name: 'punkIndex', type: 'uint256' },
      { name: 'minPrice', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawBidForPunk',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferPunk',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'punkIndex', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const satisfies Abi

const stashOrderAbi = [
  { name: 'numberOfUnits', type: 'uint16' },
  { name: 'pricePerUnit', type: 'uint80' },
  { name: 'auction', type: 'address' },
] as const

const stashPunkBidAbi = [
  { name: 'order', type: 'tuple', components: stashOrderAbi },
  { name: 'accountNonce', type: 'uint256' },
  { name: 'bidNonce', type: 'uint256' },
  { name: 'expiration', type: 'uint256' },
  { name: 'root', type: 'bytes32' },
] as const

export const stashFactoryAbi = [
  {
    type: 'function',
    name: 'currentVersion',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'implementations',
    inputs: [{ name: 'version', type: 'uint256' }],
    outputs: [{ name: 'implementation', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'stashAddressFor',
    inputs: [{ name: 'stashOwner', type: 'address' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerHasDeployed',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isStash',
    inputs: [{ name: 'stashAddress', type: 'address' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isAuction',
    inputs: [{ name: 'auctionAddress', type: 'address' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'stashVerifier',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: 'result', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownershipHandoverExpiresAt',
    inputs: [{ name: 'pendingOwner', type: 'address' }],
    outputs: [{ name: 'result', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'rolesOf',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: 'roles', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasAllRoles',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'roles', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasAnyRole',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'roles', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deployStash',
    inputs: [{ name: '_owner', type: 'address' }],
    outputs: [{ name: 'deployedAddress', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'upgradeStash',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addVersion',
    inputs: [{ name: 'implementation', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAuction',
    inputs: [
      { name: 'auction', type: 'address' },
      { name: '_isAuction', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'requestOwnershipHandover',
    inputs: [],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'completeOwnershipHandover',
    inputs: [{ name: 'pendingOwner', type: 'address' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'cancelOwnershipHandover',
    inputs: [],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'grantRoles',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'roles', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'revokeRoles',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'roles', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'renounceRoles',
    inputs: [{ name: 'roles', type: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
] as const satisfies Abi

export const stashAbi = [
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'version',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'punkAccountNonce',
    inputs: [],
    outputs: [{ type: 'uint56' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkBidNonceUsesRemaining',
    inputs: [{ name: 'punkBidNonce', type: 'uint256' }],
    outputs: [{ name: 'usesRemaining', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'usedPunkBidNonces',
    inputs: [{ name: 'punkBidNonce', type: 'uint256' }],
    outputs: [{ name: 'isUsed', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paymentTokenToOrders',
    inputs: [
      { name: 'paymentToken', type: 'address' },
      { name: 'index', type: 'uint256' },
    ],
    outputs: stashOrderAbi,
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOrder',
    inputs: [{ name: 'auction', type: 'address' }],
    outputs: [{ name: 'order', type: 'tuple', components: stashOrderAbi }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalLocked',
    inputs: [{ name: 'tokenAddress', type: 'address' }],
    outputs: [{ name: 'lockedAmount', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'availableLiquidity',
    inputs: [{ name: 'tokenAddress', type: 'address' }],
    outputs: [{ name: 'availableAmount', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'availableLiquidityWETHAndETH',
    inputs: [],
    outputs: [{ name: 'availableAmount', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [{ name: '_owner', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'placeOrder',
    inputs: [
      { name: 'pricePerUnit', type: 'uint80' },
      { name: 'numberOfUnits', type: 'uint16' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'processOrder',
    inputs: [
      { name: 'costPerUnit', type: 'uint80' },
      { name: 'numberOfUnits', type: 'uint16' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'processPunkBid',
    inputs: [
      { name: 'bid', type: 'tuple', components: stashPunkBidAbi },
      { name: 'punkIndex', type: 'uint256' },
      { name: 'signature', type: 'bytes' },
      { name: 'proof', type: 'bytes32[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelPunkBid',
    inputs: [{ name: 'bidNonce', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelAllPunkBids',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'wrapPunk',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [
      { name: 'tokenAddress', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawERC721',
    inputs: [
      { name: 'tokenAddress', type: 'address' },
      { name: 'tokenIds', type: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawERC1155',
    inputs: [
      { name: 'tokenAddress', type: 'address' },
      { name: 'tokenIds', type: 'uint256[]' },
      { name: 'amounts', type: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawPunks',
    inputs: [{ name: 'tokenIds', type: 'uint256[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onERC1155Received',
    inputs: [
      { type: 'address' },
      { type: 'address' },
      { type: 'uint256' },
      { type: 'uint256' },
      { type: 'bytes' },
    ],
    outputs: [{ type: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onERC1155BatchReceived',
    inputs: [
      { type: 'address' },
      { type: 'address' },
      { type: 'uint256[]' },
      { type: 'uint256[]' },
      { type: 'bytes' },
    ],
    outputs: [{ type: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onERC721Received',
    inputs: [
      { type: 'address' },
      { type: 'address' },
      { type: 'uint256' },
      { type: 'bytes' },
    ],
    outputs: [{ type: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
] as const satisfies Abi

const punksFilterAbi = [
  { name: 'requiredTraitMask', type: 'uint256' },
  { name: 'forbiddenTraitMask', type: 'uint256' },
  { name: 'anyOfTraitMask', type: 'uint256' },
  { name: 'requiredColorMask', type: 'uint256' },
  { name: 'forbiddenColorMask', type: 'uint256' },
  { name: 'anyOfColorMask', type: 'uint256' },
  { name: 'minPixelCount', type: 'uint16' },
  { name: 'maxPixelCount', type: 'uint16' },
  { name: 'minColorCount', type: 'uint8' },
  { name: 'maxColorCount', type: 'uint8' },
] as const

const lotItemAbi = [
  { name: 'standard', type: 'uint8' },
  { name: 'punkId', type: 'uint16' },
  { name: 'weightBps', type: 'uint16' },
] as const

const offerSlotAbi = [
  { name: 'criteria', type: 'tuple', components: punksFilterAbi },
  { name: 'standard', type: 'uint8' },
  { name: 'includeIds', type: 'uint16[]' },
  { name: 'excludeIds', type: 'uint16[]' },
] as const

export const punksAuctionAbi = [
  { type: 'error', name: 'AuctionAlreadySettled', inputs: [] },
  { type: 'error', name: 'AuctionDoesNotExist', inputs: [] },
  { type: 'error', name: 'AuctionNotActive', inputs: [] },
  { type: 'error', name: 'AuctionNotApproved', inputs: [] },
  { type: 'error', name: 'AuctionNotComplete', inputs: [] },
  {
    type: 'error',
    name: 'BuyerNotAllowed',
    inputs: [{ name: 'allowed', type: 'address' }],
  },
  { type: 'error', name: 'DuplicateLotItem', inputs: [] },
  { type: 'error', name: 'FailedWithdrawal', inputs: [] },
  { type: 'error', name: 'IncorrectPayment', inputs: [] },
  { type: 'error', name: 'InvalidAmount', inputs: [] },
  { type: 'error', name: 'InvalidColorCountRange', inputs: [] },
  { type: 'error', name: 'InvalidColorMask', inputs: [] },
  { type: 'error', name: 'InvalidItemCount', inputs: [] },
  { type: 'error', name: 'InvalidPixelCountRange', inputs: [] },
  { type: 'error', name: 'InvalidSlotCount', inputs: [] },
  { type: 'error', name: 'InvalidTraitMask', inputs: [] },
  { type: 'error', name: 'InvalidWeights', inputs: [] },
  { type: 'error', name: 'ListingNotValid', inputs: [] },
  {
    type: 'error',
    name: 'ListingPriceMismatch',
    inputs: [
      { name: 'expectedListingWei', type: 'uint96' },
      { name: 'actualListingWei', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'ListingPriceTooHigh', inputs: [] },
  { type: 'error', name: 'LotNotFound', inputs: [] },
  { type: 'error', name: 'LotNotStale', inputs: [] },
  { type: 'error', name: 'LotTooLargeForInstantAccept', inputs: [] },
  {
    type: 'error',
    name: 'MinimumBidNotMet',
    inputs: [
      { name: 'minBidWei', type: 'uint96' },
      { name: 'actualBidWei', type: 'uint96' },
    ],
  },
  { type: 'error', name: 'MultiSlotOfferRequiresLot', inputs: [] },
  { type: 'error', name: 'NoBalanceToWithdraw', inputs: [] },
  { type: 'error', name: 'NotAuctions', inputs: [] },
  { type: 'error', name: 'NotOfferer', inputs: [] },
  { type: 'error', name: 'NotSeller', inputs: [] },
  {
    type: 'error',
    name: 'OfferAmountBelowMinimum',
    inputs: [
      { name: 'minAmountWei', type: 'uint96' },
      { name: 'actualAmountWei', type: 'uint96' },
    ],
  },
  { type: 'error', name: 'OfferNotActive', inputs: [] },
  { type: 'error', name: 'OfferStandardMismatch', inputs: [] },
  {
    type: 'error',
    name: 'PunkAlreadyInLot',
    inputs: [{ name: 'lotId', type: 'uint256' }],
  },
  { type: 'error', name: 'PunkExcluded', inputs: [] },
  { type: 'error', name: 'PunkNotInVault', inputs: [] },
  { type: 'error', name: 'PunkNotMatched', inputs: [] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  {
    type: 'error',
    name: 'ReserveMismatch',
    inputs: [
      { name: 'expectedReserveWei', type: 'uint96' },
      { name: 'actualReserveWei', type: 'uint96' },
    ],
  },
  {
    type: 'error',
    name: 'ReserveNotMet',
    inputs: [
      { name: 'reserveWei', type: 'uint96' },
      { name: 'actualWei', type: 'uint96' },
    ],
  },
  { type: 'error', name: 'SlotItemCountMismatch', inputs: [] },
  { type: 'error', name: 'TooManyIds', inputs: [] },
  { type: 'error', name: 'UnexpectedEtherSender', inputs: [] },
  { type: 'error', name: 'VaultNotDeployed', inputs: [] },
  { type: 'error', name: 'ZeroAddress', inputs: [] },
  {
    type: 'event',
    name: 'AuctionExtended',
    anonymous: false,
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'endTimestamp', type: 'uint40' },
    ],
  },
  {
    type: 'event',
    name: 'AuctionInitialised',
    anonymous: false,
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'lotId', type: 'uint256', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
      { name: 'itemCount', type: 'uint8' },
      { name: 'endTimestamp', type: 'uint40' },
    ],
  },
  {
    type: 'event',
    name: 'AuctionItemDelivered',
    anonymous: false,
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'itemIndex', type: 'uint8', indexed: true },
      { name: 'standard', type: 'uint8' },
      { name: 'punkId', type: 'uint16' },
      { name: 'recipient', type: 'address' },
      { name: 'itemWei', type: 'uint96' },
    ],
  },
  {
    type: 'event',
    name: 'AuctionSettled',
    anonymous: false,
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'winner', type: 'address', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
      { name: 'finalWei', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'Bid',
    anonymous: false,
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'bidder', type: 'address', indexed: true },
      { name: 'amountWei', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'Credited',
    anonymous: false,
    inputs: [
      { name: 'account', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'LotCancelled',
    anonymous: false,
    inputs: [{ name: 'lotId', type: 'uint256', indexed: true }],
  },
  {
    type: 'event',
    name: 'LotCleared',
    anonymous: false,
    inputs: [
      { name: 'lotId', type: 'uint256', indexed: true },
      { name: 'cleaner', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'LotCreated',
    anonymous: false,
    inputs: [
      { name: 'lotId', type: 'uint256', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
      { name: 'itemHash', type: 'bytes32', indexed: true },
      { name: 'itemCount', type: 'uint8' },
      { name: 'reserveWei', type: 'uint96' },
      { name: 'onlySellTo', type: 'address' },
    ],
  },
  {
    type: 'event',
    name: 'LotItemDetail',
    anonymous: false,
    inputs: [
      { name: 'lotId', type: 'uint256', indexed: true },
      { name: 'itemIndex', type: 'uint8', indexed: true },
      { name: 'standard', type: 'uint8' },
      { name: 'punkId', type: 'uint16' },
      { name: 'weightBps', type: 'uint16' },
    ],
  },
  {
    type: 'event',
    name: 'LotUpdated',
    anonymous: false,
    inputs: [
      { name: 'lotId', type: 'uint256', indexed: true },
      { name: 'reserveWei', type: 'uint96' },
      { name: 'onlySellTo', type: 'address' },
    ],
  },
  {
    type: 'event',
    name: 'OfferAccepted',
    anonymous: false,
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true },
      { name: 'punkId', type: 'uint256', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
      { name: 'offerer', type: 'address' },
      { name: 'amountWei', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'OfferAcceptedFromLot',
    anonymous: false,
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true },
      { name: 'lotId', type: 'uint256', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
      { name: 'offerer', type: 'address' },
      { name: 'amountWei', type: 'uint96' },
    ],
  },
  {
    type: 'event',
    name: 'OfferAmountAdjusted',
    anonymous: false,
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true },
      { name: 'newAmountWei', type: 'uint96' },
    ],
  },
  {
    type: 'event',
    name: 'OfferAuctionInitialised',
    anonymous: false,
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true },
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'lotId', type: 'uint256', indexed: true },
      { name: 'seller', type: 'address' },
      { name: 'offerer', type: 'address' },
      { name: 'amountWei', type: 'uint96' },
    ],
  },
  {
    type: 'event',
    name: 'OfferCancelled',
    anonymous: false,
    inputs: [{ name: 'offerId', type: 'uint256', indexed: true }],
  },
  {
    type: 'event',
    name: 'OfferPlaced',
    anonymous: false,
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true },
      { name: 'offerer', type: 'address', indexed: true },
      { name: 'amountWei', type: 'uint96' },
      { name: 'slotCount', type: 'uint8' },
    ],
  },
  {
    type: 'event',
    name: 'OfferSlotDetail',
    anonymous: false,
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true },
      { name: 'slotIndex', type: 'uint8', indexed: true },
      { name: 'standard', type: 'uint8' },
      { name: 'criteria', type: 'tuple', components: punksFilterAbi },
      { name: 'includeIds', type: 'uint16[]' },
      { name: 'excludeIds', type: 'uint16[]' },
    ],
  },
  {
    type: 'event',
    name: 'Withdrawal',
    anonymous: false,
    inputs: [
      { name: 'account', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'PUNKS',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PUNKS_V1',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'VAULTS',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ESCROW',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PUNKS_DATA',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lastLotId',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lastAuctionId',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lastOfferId',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lots',
    inputs: [{ name: 'lotId', type: 'uint256' }],
    outputs: [
      { name: 'seller', type: 'address' },
      { name: 'reserveWei', type: 'uint96' },
      { name: 'onlySellTo', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'auctions',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [
      { name: 'seller', type: 'address' },
      { name: 'latestBidder', type: 'address' },
      { name: 'latestBidWei', type: 'uint96' },
      { name: 'endTimestamp', type: 'uint40' },
      { name: 'settled', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'offers',
    inputs: [{ name: 'offerId', type: 'uint256' }],
    outputs: [
      { name: 'amountWei', type: 'uint96' },
      { name: 'offerer', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLotItems',
    inputs: [{ name: 'lotId', type: 'uint256' }],
    outputs: [{ type: 'tuple[]', components: lotItemAbi }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAuctionItems',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [{ type: 'tuple[]', components: lotItemAbi }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOfferSlots',
    inputs: [{ name: 'offerId', type: 'uint256' }],
    outputs: [{ type: 'tuple[]', components: offerSlotAbi }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'activeLotFor',
    inputs: [
      { name: 'seller', type: 'address' },
      { name: 'standard', type: 'uint8' },
      { name: 'punkId', type: 'uint16' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lotForPunk',
    inputs: [{ type: 'bytes32' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'currentMinBidWei',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [{ type: 'uint96' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'auctionActive',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'endTimestampOf',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [{ type: 'uint40' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'balances',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createLot',
    inputs: [
      { name: 'items', type: 'tuple[]', components: lotItemAbi },
      { name: 'reserveWei', type: 'uint96' },
      { name: 'onlySellTo', type: 'address' },
    ],
    outputs: [{ name: 'lotId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateLot',
    inputs: [
      { name: 'lotId', type: 'uint256' },
      { name: 'reserveWei', type: 'uint96' },
      { name: 'onlySellTo', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelLot',
    inputs: [{ name: 'lotId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'clearStaleLot',
    inputs: [{ name: 'lotId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'clearStaleLots',
    inputs: [{ name: 'lotIds', type: 'uint256[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'openAuction',
    inputs: [
      { name: 'lotId', type: 'uint256' },
      { name: 'expectedReserveWei', type: 'uint96' },
    ],
    outputs: [{ name: 'auctionId', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'bid',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'settle',
    inputs: [{ name: 'auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'placeOffer',
    inputs: [
      { name: 'amountWei', type: 'uint96' },
      { name: 'slots', type: 'tuple[]', components: offerSlotAbi },
    ],
    outputs: [{ name: 'offerId', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'cancelOffer',
    inputs: [{ name: 'offerId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'adjustOfferAmount',
    inputs: [
      { name: 'offerId', type: 'uint256' },
      { name: 'newAmountWei', type: 'uint96' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'acceptOffer',
    inputs: [
      { name: 'offerId', type: 'uint256' },
      { name: 'punkId', type: 'uint16' },
      { name: 'expectedListingWei', type: 'uint96' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'acceptOfferFromLot',
    inputs: [
      { name: 'offerId', type: 'uint256' },
      { name: 'lotId', type: 'uint256' },
      { name: 'minAmountWei', type: 'uint96' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'startAuctionFromOffer',
    inputs: [
      { name: 'offerId', type: 'uint256' },
      { name: 'lotId', type: 'uint256' },
      { name: 'minAmountWei', type: 'uint96' },
    ],
    outputs: [{ name: 'auctionId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createLotAndAcceptOffer',
    inputs: [
      { name: 'items', type: 'tuple[]', components: lotItemAbi },
      { name: 'offerId', type: 'uint256' },
      { name: 'minAmountWei', type: 'uint96' },
    ],
    outputs: [{ name: 'lotId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createLotAndStartAuction',
    inputs: [
      { name: 'items', type: 'tuple[]', components: lotItemAbi },
      { name: 'offerId', type: 'uint256' },
      { name: 'minAmountWei', type: 'uint96' },
    ],
    outputs: [{ name: 'auctionId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
] as const satisfies Abi

export const punkVaultFactoryAbi = [
  {
    type: 'function',
    name: 'IMPLEMENTATION',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'predictVault',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ensureVault',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: 'vault', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'ensureMyVault',
    inputs: [{ name: 'operators', type: 'address[]' }],
    outputs: [{ name: 'vault', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'VaultDeployed',
    inputs: [
      { name: 'owner', type: 'address', indexed: true },
      { name: 'vault', type: 'address', indexed: true },
    ],
  },
] as const satisfies Abi

export const punkVaultAbi = [
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'FACTORY',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setOperator',
    inputs: [
      { name: 'operator', type: 'address' },
      { name: 'approved', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isOperator',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferPunk',
    inputs: [
      { name: 'market', type: 'address' },
      { name: 'punkIndex', type: 'uint256' },
      { name: 'to', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'offerPunkForSale',
    inputs: [
      { name: 'market', type: 'address' },
      { name: 'punkIndex', type: 'uint256' },
      { name: 'minSalePriceWei', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'offerPunkForSaleToAddress',
    inputs: [
      { name: 'market', type: 'address' },
      { name: 'punkIndex', type: 'uint256' },
      { name: 'minSalePriceWei', type: 'uint256' },
      { name: 'toAddress', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'punkNoLongerForSale',
    inputs: [
      { name: 'market', type: 'address' },
      { name: 'punkIndex', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'acceptBidForPunk',
    inputs: [
      { name: 'market', type: 'address' },
      { name: 'punkIndex', type: 'uint256' },
      { name: 'minPrice', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'buyPunk',
    inputs: [
      { name: 'market', type: 'address' },
      { name: 'punkIndex', type: 'uint256' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'enterBidForPunk',
    inputs: [
      { name: 'market', type: 'address' },
      { name: 'punkIndex', type: 'uint256' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'withdrawBidForPunk',
    inputs: [
      { name: 'market', type: 'address' },
      { name: 'punkIndex', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawFromMarket',
    inputs: [{ name: 'market', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawFromMarketTo',
    inputs: [
      { name: 'market', type: 'address' },
      { name: 'recipient', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'stash',
    inputs: [{ name: 'punkIndex', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'execute',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'value', type: 'uint256' },
      { name: 'data', type: 'bytes' },
    ],
    outputs: [{ type: 'bytes' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'executeBatch',
    inputs: [
      {
        name: 'calls',
        type: 'tuple[]',
        components: [
          { name: 'target', type: 'address' },
          { name: 'value', type: 'uint256' },
          { name: 'data', type: 'bytes' },
        ],
      },
    ],
    outputs: [{ type: 'bytes[]' }],
    stateMutability: 'payable',
  },
  {
    type: 'event',
    name: 'OperatorSet',
    inputs: [
      { name: 'operator', type: 'address', indexed: true },
      { name: 'approved', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Executed',
    inputs: [
      { name: 'target', type: 'address', indexed: true },
      { name: 'value', type: 'uint256', indexed: false },
      { name: 'data', type: 'bytes', indexed: false },
    ],
  },
] as const satisfies Abi

export const punksV1MarketAbi = [
  { type: 'error', name: 'AdjustmentTooLarge', inputs: [] },
  { type: 'error', name: 'BidNotActive', inputs: [] },
  { type: 'error', name: 'FailedWithdrawal', inputs: [] },
  { type: 'error', name: 'IncorrectPayment', inputs: [] },
  { type: 'error', name: 'InvalidAmount', inputs: [] },
  { type: 'error', name: 'InvalidColorCountRange', inputs: [] },
  { type: 'error', name: 'InvalidColorMask', inputs: [] },
  { type: 'error', name: 'InvalidPixelCountRange', inputs: [] },
  { type: 'error', name: 'InvalidTraitMask', inputs: [] },
  { type: 'error', name: 'ListingNotValid', inputs: [] },
  {
    type: 'error',
    name: 'ListingPriceMismatch',
    inputs: [
      { name: 'expectedListingWei', type: 'uint96' },
      { name: 'actualListingWei', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'ListingPriceTooHigh', inputs: [] },
  { type: 'error', name: 'NoBalanceToWithdraw', inputs: [] },
  { type: 'error', name: 'NotBidder', inputs: [] },
  { type: 'error', name: 'PunkCriteriaMismatch', inputs: [] },
  { type: 'error', name: 'PunkExcluded', inputs: [] },
  { type: 'error', name: 'PunkNotIncluded', inputs: [] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  { type: 'error', name: 'TooManyIds', inputs: [] },
  { type: 'error', name: 'UnexpectedEtherSender', inputs: [] },
  { type: 'error', name: 'ZeroAddress', inputs: [] },
  {
    type: 'event',
    name: 'BidAccepted',
    anonymous: false,
    inputs: [
      { name: 'bidId', type: 'uint256', indexed: true },
      { name: 'punkId', type: 'uint256', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
      { name: 'bidder', type: 'address' },
      { name: 'caller', type: 'address' },
      { name: 'listingWei', type: 'uint96' },
      { name: 'bidWei', type: 'uint96' },
      { name: 'settlementWei', type: 'uint96' },
    ],
  },
  {
    type: 'event',
    name: 'BidAdjusted',
    anonymous: false,
    inputs: [
      { name: 'bidId', type: 'uint256', indexed: true },
      { name: 'newBidWei', type: 'uint96' },
    ],
  },
  {
    type: 'event',
    name: 'BidCancelled',
    anonymous: false,
    inputs: [{ name: 'bidId', type: 'uint256', indexed: true }],
  },
  {
    type: 'event',
    name: 'BidPlaced',
    anonymous: false,
    inputs: [
      { name: 'bidId', type: 'uint256', indexed: true },
      { name: 'bidder', type: 'address', indexed: true },
      { name: 'bidWei', type: 'uint96' },
      { name: 'settlementWei', type: 'uint96' },
      {
        name: 'criteria',
        type: 'tuple',
        components: [
          { name: 'requiredTraitMask', type: 'uint256' },
          { name: 'forbiddenTraitMask', type: 'uint256' },
          { name: 'anyOfTraitMask', type: 'uint256' },
          { name: 'requiredColorMask', type: 'uint256' },
          { name: 'forbiddenColorMask', type: 'uint256' },
          { name: 'anyOfColorMask', type: 'uint256' },
          { name: 'minPixelCount', type: 'uint16' },
          { name: 'maxPixelCount', type: 'uint16' },
          { name: 'minColorCount', type: 'uint8' },
          { name: 'maxColorCount', type: 'uint8' },
        ],
      },
      { name: 'includeIds', type: 'uint16[]' },
      { name: 'excludeIds', type: 'uint16[]' },
    ],
  },
  {
    type: 'event',
    name: 'Credited',
    anonymous: false,
    inputs: [
      { name: 'account', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'PunkPurchased',
    anonymous: false,
    inputs: [
      { name: 'punkId', type: 'uint256', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
      { name: 'recipient', type: 'address', indexed: true },
      { name: 'caller', type: 'address' },
      { name: 'listingWei', type: 'uint96' },
    ],
  },
  {
    type: 'event',
    name: 'Withdrawal',
    anonymous: false,
    inputs: [
      { name: 'account', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'PUNKS_CRITERIA',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PUNKS_DATA',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PUNKS_V1',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PUNKS_VISUAL',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'acceptBid',
    inputs: [
      { name: 'bidId', type: 'uint256' },
      { name: 'punkId', type: 'uint16' },
      { name: 'expectedListingWei', type: 'uint96' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'adjustBidPrice',
    inputs: [
      { name: 'bidId', type: 'uint256' },
      { name: 'weiToAdjust', type: 'uint96' },
      { name: 'increase', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'balances',
    inputs: [{ type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'bids',
    inputs: [{ name: 'bidId', type: 'uint256' }],
    outputs: [
      { name: 'bidWei', type: 'uint96' },
      { name: 'settlementWei', type: 'uint96' },
      { name: 'bidder', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'bidsMatchingPunk',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'fromId', type: 'uint256' },
      { name: 'count', type: 'uint256' },
    ],
    outputs: [
      { name: 'bidIds', type: 'uint256[]' },
      { name: 'nextId', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'buyPunk',
    inputs: [
      { name: 'punkId', type: 'uint16' },
      { name: 'expectedListingWei', type: 'uint96' },
      { name: 'recipient', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'cancelBid',
    inputs: [{ name: 'bidId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getBidCriteria',
    inputs: [{ name: 'bidId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'requiredTraitMask', type: 'uint256' },
          { name: 'forbiddenTraitMask', type: 'uint256' },
          { name: 'anyOfTraitMask', type: 'uint256' },
          { name: 'requiredColorMask', type: 'uint256' },
          { name: 'forbiddenColorMask', type: 'uint256' },
          { name: 'anyOfColorMask', type: 'uint256' },
          { name: 'minPixelCount', type: 'uint16' },
          { name: 'maxPixelCount', type: 'uint16' },
          { name: 'minColorCount', type: 'uint8' },
          { name: 'maxColorCount', type: 'uint8' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBidExcludeIds',
    inputs: [{ name: 'bidId', type: 'uint256' }],
    outputs: [{ type: 'uint16[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBidIncludeIds',
    inputs: [{ name: 'bidId', type: 'uint256' }],
    outputs: [{ type: 'uint16[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lastBidId',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'matchesPunk',
    inputs: [
      { name: 'bidId', type: 'uint256' },
      { name: 'punkId', type: 'uint16' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'placeBid',
    inputs: [
      { name: 'bidWei', type: 'uint96' },
      { name: 'settlementWei', type: 'uint96' },
      {
        name: 'criteria',
        type: 'tuple',
        components: [
          { name: 'requiredTraitMask', type: 'uint256' },
          { name: 'forbiddenTraitMask', type: 'uint256' },
          { name: 'anyOfTraitMask', type: 'uint256' },
          { name: 'requiredColorMask', type: 'uint256' },
          { name: 'forbiddenColorMask', type: 'uint256' },
          { name: 'anyOfColorMask', type: 'uint256' },
          { name: 'minPixelCount', type: 'uint16' },
          { name: 'maxPixelCount', type: 'uint16' },
          { name: 'minColorCount', type: 'uint8' },
          { name: 'maxColorCount', type: 'uint8' },
        ],
      },
      { name: 'includeIds', type: 'uint16[]' },
      { name: 'excludeIds', type: 'uint16[]' },
    ],
    outputs: [{ name: 'bidId', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const satisfies Abi

export const punksV1WrapperAbi = [
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerOf',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenURI',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'exists',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getApproved',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isApprovedForAll',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'operator', type: 'address' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'punkAddress',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setApprovalForAll',
    inputs: [
      { name: 'operator', type: 'address' },
      { name: 'approved', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
      { name: 'data', type: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'wrap',
    inputs: [{ name: '_punkId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'unwrap',
    inputs: [{ name: '_punkId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Approval',
    anonymous: false,
    inputs: [
      { name: 'owner', type: 'address', indexed: true },
      { name: 'approved', type: 'address', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'ApprovalForAll',
    anonymous: false,
    inputs: [
      { name: 'owner', type: 'address', indexed: true },
      { name: 'operator', type: 'address', indexed: true },
      { name: 'approved', type: 'bool' },
    ],
  },
  {
    type: 'event',
    name: 'Transfer',
    anonymous: false,
    inputs: [
      { name: 'from', type: 'address', indexed: true },
      { name: 'to', type: 'address', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
    ],
  },
] as const satisfies Abi

export const unwrapV1PunksAbi = [
  {
    type: 'function',
    name: 'unwrap',
    inputs: [{ name: 'punkIds', type: 'uint16[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'WRAPPER',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PUNKS_V1',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'PunksUnwrapped',
    anonymous: false,
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'punkIds', type: 'uint16[]' },
    ],
  },
  { type: 'error', name: 'NoPunkIds', inputs: [] },
  { type: 'error', name: 'NotPunkOwner', inputs: [] },
] as const satisfies Abi
